import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const telegram=fs.readFileSync(new URL('../backend/telegram-format.js',import.meta.url),'utf8');
assert.ok(html.includes('<th>요청내용</th>'));
assert.ok(html.includes('id="detailDialogTitle"'));
assert.ok(app.includes('function requestDetailItems'));
assert.ok(app.includes('문의내용'));
assert.ok(app.includes('반품사유'));
assert.ok(app.includes('교환사유'));
assert.ok(app.includes('request-detail-open'));
assert.ok(css.includes('.request-detail-preview'));
assert.ok(css.includes('.detail-long-text'));
assert.ok(telegram.includes('💬 문의내용'));
assert.ok(telegram.includes('↩️ 반품사유'));
assert.ok(telegram.includes('🔄 교환사유'));
console.log('v7.7.29 CS detail display contract passed');
