import assert from 'node:assert/strict';
import fs from 'node:fs';
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.ok(html.includes('v7.7.31 쿠팡 문의 2종 분리'));
assert.ok(html.includes('id="openMarketBtn"'));
assert.ok(app.includes('IntersectionObserver'));
assert.ok(app.includes('data-src='));
assert.ok(app.includes('decoding="async"'));
assert.ok(app.includes('fetchpriority="low"'));
assert.ok(app.includes('MOBILE_PAGE_SIZE=20'));
assert.ok(!app.includes('order.syncedAt'));
assert.ok(!app.includes('order.statusUpdatedAt'));
assert.ok(app.includes('MARKET_SELLER_PORTALS'));
assert.ok(app.includes('openMarketplaceForOrder'));
assert.ok(app.includes("coupang:'https://wing.coupang.com/'"));
assert.ok(app.includes("smartstore:'https://sell.smartstore.naver.com/'"));
assert.ok(app.includes("lotteon:'https://store.lotteon.com/'"));
assert.ok(css.includes('.product-market-link'));
assert.ok(css.includes('content-visibility:auto'));
assert.ok(css.includes('.market-open-btn'));
console.log('v7.7.30 fast scroll and marketplace action contract passed');
